# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#hero"
  weight = 10

[[main]]
  name = "Posts"
  url = "post/"
  weight = 20

[[main]]
  name = "Projects"
  url = "projects/"
  weight = 30

[[main]]
  name = "Publications"
  url = "featured/"
  weight = 40

[[main]]
  name = "พิธีการศุลกากร"
  url = "customs/"
  weight = 50
<<<<<<< HEAD

  [[main.import]]
  name = "Import"
  url = "customs/import/"
  weight = 55

=======
>>>>>>> f3564cb4857ce369836db0793180c74731a0885e
  


[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
