# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#hero"
  weight = 10

[[main]]
  name = "พิธีการศุลกากร"
  url = "customs/import-export/"
  weight = 20

[[main]]
  parent = "พิธีการศุลกากร"
  name = "การนำเข้า"
  url = "customs/import-export/import/"
  weight = 21

[[main]]
  parent = "พิธีการศุลกากร"
  name = "การส่งออก"
  url = "customs/import-export/export/"
  weight = 22
[[main]]
  parent = "พิธีการศุลกากร"
  name = "สินค้าถ่ายลำ/ผ่านแดน"
  url = "customs/import-export/transit/"
  weight = 23
[[main]]
  parent ="พิธีการศุลกากร"
  name = "สิทธิประโยชน์ทางภาษี"
  url = "customs/tax-incentive/"
  weight = 24
[[main]]
  parent = "พิธีการศุลกากร"
  name = "สิทธิพิเศษทางการค้า"
  url = "customs/free-trade/"
  weight = 25


[[main]]
  name = "เรื่องน่ารู้"
  url = "customs/"
  weight = 30


[[main]]
  parent = "เรื่องน่ารู้"
  name = "ใบอนุญาต/ใบรับรอง"
  url = "customs/restricted-goods/"
  weight = 31

[[main]]
  parent = "เรื่องน่ารู้"
  name = "พิกัดศุลกากร"
  url = "customs/customs-tariff/"
  weight = 32
[[main]]
  parent = "เรื่องน่ารู้"
  name = "ราคาศุลกากร"
  url = "customs/price/"
  weight = 33

[[main]]
  parent = "เรื่องน่ารู้"
  name = "Reference data"
  url = "https://ecs-support.github.io/KM/reference/"
  weight = 40

[[main]]
  parent = "เรื่องน่ารู้"
  name = "ผู้ประกอบการ"
  url = "customs/company/"
  weight = 45

[[main]]
  parent = "เรื่องน่ารู้"
  name = "เกี่ยวกับกรมศุลกากร"
  url = "customs/customs-dept/"
  weight = 46


[[main]]
  name = "ข่าวสารบทความ"
  url = "post/"
  weight = 60
  

[[main]]

  name = "ประกาศ/กฎหมาย"
  url = "post/announcement/customs/"
  weight = 70

[[main]]
  parent = "ประกาศ/กฎหมาย"
  name = "กรมศุลกากร"
  url = "post/announcement/customs/"
  weight = 71




[[main]]
  name = "FAQ"
  url = "customs/faq/"
  weight = 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
